mail:
  address:
    admin: asd@gmail.com

jwt:
  secret-key: fighting033
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
debug: false
management.endpoints.web.exposure.include: "*"


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: uno
    password: thisisTESTpw!#%&
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always

