spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        default_batch_fetch_size: 1000 # onetomany paging 시 중복제거하여 최적화 위해
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: dnjsdyd0670@gmail.com  # 변경 가능

jwt:
  secret-key: fighting033   # 변경 가능
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420