mail:
  address:
    admin: asd@gmail.com

jwt:
  secret-key: fighting033
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420


spring:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

---
spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
    port: ${PORT}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always
server:
  port: ${port:8080}



